# ENV Variables required (no fallback):
# DJANGO_SECRET_KEY
# TARGET_ENV

version: '3.4'
  
services:
  postgres:
    logging:
      driver: none
    volumes:
      - db-data_dev:/var/lib/postgresql/data
  redis:
    logging:
      driver: none
    volumes:
      - redis_data:/data
  ur_l:
    environment:
      - COV_FAIL_THRESHOLD=90
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:?Django Secret}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - UR_L_PORT=${UR_L_PORT:-8001}
    stdin_open: true
    ports:
      - "${UR_L_PORT:-8001}:${UR_L_PORT:-8001}"
    tty: true
    volumes:
      - ./app:/dev_app

volumes:
  db-data_dev:
    driver: local
  redis_data:
    driver: local
