# ENV Variables required (no fallback):
# DJANGO_SECRET_KEY
version: '3.4'
  
services:
  postgres:
    image: postgres:${POSTGRES_TAG:-latest}
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}
  redis:
    image: redis:${REDIS_TAG:-latest}
    volumes:
      - redis_data:/data
  ur_l:
    image: url_l_${TARGET_ENV:-production}
    build:
      dockerfile: ./docker/Dockerfile
      context: .
      target: ${TARGET_ENV:-production}
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - PORT=${UR_L_PORT:-8000}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:?Django Secret}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: runserver
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

volumes:
  db-data:
    driver: local
  redis_data:
    driver: local
