# Generated by Django 3.1 on 2022-08-26 22:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollisionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=7)),
                ('collision_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('token', models.CharField(db_index=True, help_text='Type `random` or `r` to generate random token', max_length=7, primary_key=True, serialize=False)),
                ('long_url', models.CharField(max_length=500, validators=[django.core.validators.URLValidator()])),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('click_limit', models.IntegerField(default=0, help_text='Remove url when this is reached')),
            ],
        ),
        migrations.CreateModel(
            name='ClickLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0')),
                ('http_referer', models.CharField(blank=True, max_length=500)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='api.url')),
            ],
        ),
    ]
