name: Bandit Security

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Bandit
      uses: Joel-hanson/bandit-report-artifacts@V1
      with:
        python_version: 3.8
        project_path: ./app

    - name: Security check report artifacts
      uses: actions/upload-artifact@v1
      # if: failure()
      with:
        name: Security report
        path: output/security_report.txt
