name: Docker Build + Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        DJANGO_SECRET_KEY: test
        UR_L_PORT: 8000
        TARGET_ENV: production
    steps:
    - uses: actions/checkout@v2

    - name: docker-compose build # Linting happens here too, see Dockerfile
      run: docker-compose -f docker-compose.yml build
    - name: docker-compose up
      run: docker-compose -f docker-compose.yml up -d
    - name: Nginx Benchmark
      run: docker exec `docker ps -qf "name=ur_l_nginx"` benchmark
    - name: docker-compose stop
      run: docker-compose stop
    - name: run tests
      run: docker-compose -f docker-compose.yml run ur_l test
