name: Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        DJANGO_SECRET_KEY: test
        UR_L_PORT: 8000
        TARGET_ENV: production
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
    steps:
    - uses: actions/checkout@v2

    - name: Build Container
      run: docker-compose -f docker-compose.yml build
    - name: Run main app
      run: docker-compose -f docker-compose.yml run -d ur_l
    - name: Run Nginx
      run: docker-compose -f docker-compose.yml run -d nginx
    - name: Run Nginx benchmark
      run: docker exec `docker ps -qf "name=ur_l_nginx"` benchmark
    - name: Stop services
      run: docker-compose stop
    - name: Run tests
      run: docker-compose -f docker-compose.yml run ur_l test
    - name: Docker setup
      run: docker login --username=$DOCKER_USER --password=$DOCKER_PASS
    - name: Docker push
      run: docker-compose push
